### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by sgehrman** [announcekitapp/announcekit-react#1]
I had a bunch of problems getting this to work by the instructions on the widget page.  Finally got it to kind of work, but when I cleared my browser cache for that page, it stopped working.  Then I tried this announcekit-react package and still can't get it working.  I see that it does create the widget div and the window.announcekit is setup.  Not sure why it's not working.  No errors in console and no network errors.

**Comment by namirali** [comment]
@sgehrman is it possible for you to share the code that you are working on or a demo page? It will much easy and quicker to see what the problem is. Thank you for creating an issue.

**Comment by sgehrman** [comment]
there is no code.  It's exactly the sample code you provide.  And in another case just using this announcekit-react.  Post an example that works.  I think the bug is on the backend.

**Comment by namirali** [comment]
@sgehrman I think you have implementation problem there. Here is more detailed tutorial how to include a ReactJS component into your apps. https://announcekit.app/docs/reactjs.

**Comment by sgehrman** [comment]
It does work randomly, then randomly fails.  For something so simplistic, and the fact I copied the code right over and it did seem to work initially makes me think it's your bug not mine.

**Comment by namirali** [comment]
@sgehrman The only reason that widget would not work is, if you specify incorrect type of widget when you initialize the script or module. 

For example, if you try to setup float type widget as badge/line widgets, it will not work.

**Comment by namirali** [comment]
@sgehrman we have just published a new version of the component, maybe it could help you with the problem that you have.

**Comment by sgehrman** [comment]
Yeah, it works!!  Thanks.
