### ISSUE TITLE
Component gets inserted at the end of the page view instead of where it's called.

### ISSUE THREAD

**Issue by altechzilla** [announcekitapp/announcekit-react#12]
Rather than being inserted inside the parent component, the embed widget gets inserted at the very end of the page. @eknkc @namirali 

<img width="896" alt="image" src="https://user-images.githubusercontent.com/8274669/88919531-c7d90680-d25a-11ea-809f-b083687b74f4.png">

**Comment by namirali** [comment]
@altechzilla for embed widget type you need to set embedWidget={true} property, otherwise widget.js will consider the widget as a badge. https://codesandbox.io/s/amazing-pare-hslzt?file=/src/App.tsx

is it possible to share the implementation sample that you have?
