### ISSUE TITLE
On our app, the booster header is adding a blank margin with the same size 

### ISSUE THREAD

**Issue by bbenoist** [announcekitapp/announcekit-react#27]
As [you can see on this preview deployment](https://labelflow-git-feature-announcements-labelflow.vercel.app) of our React website, the booster header is adding a blank margin on top of the body.

![image](https://user-images.githubusercontent.com/2091902/149346948-06263b0f-cf85-45fa-a55b-e2e705ec2a69.png)

Here is the draft pull-request if you want to help: https://github.com/labelflow/labelflow/pull/787

Blocks https://github.com/labelflow/labelflow/issues/635

**Comment by namirali** [comment]
The main reason for that the body element has **position:relative** which prevents the bar filling the gap.

Now if there is an announcement bar booster, our widget script appends a temporary class which sets body **position: static** as it is a default property for the elements, removes the class on close/timeout.

Should be fixed now.
