### ISSUE TITLE
Label filtering is not working

### ISSUE THREAD

**Issue by bbenoist** [announcekitapp/announcekit-react#28]
The `labels` property don't seems to work. Even in the example you've linked in the official documentation if we change the `fix` label filter to `improvement` 😿 

See forked example here: https://codesandbox.io/s/announcekit-react-2-0-demo-forked-5t7gf

Am I missing something?

_This issue is not linked to #26_

**Comment by namirali** [comment]
Hey @bbenoist just checked the forked example and it looks fine, it filters the announcements based on labels https://cln.sh/ripdEI 

which version do you use have on your webapp?

**Comment by bbenoist** [comment]
@namirali The forked example I've given does not seems to be working for me. A post with the label `fix` is being displayed whereas I've only allowed `improvement`:

![image](https://user-images.githubusercontent.com/2091902/153011191-b3418ec7-517e-45eb-8b7c-1b74084bb75a.png)

As for the version, we're using 2.7.1: https://github.com/labelflow/labelflow/blob/main/typescript/web/package.json#L50

**Comment by namirali** [comment]
There is another widget code below the sample, so I guess it may trigger the announcement bar booster with the FIX label.

Another issue could be that there is no any post with Improvement tag marked as “Announcement Bar” booster on the editor.

**Comment by joeleduardo** [comment]
Are there a fix for this bug?

**Comment by yigitfindikli** [comment]
Hello Everyone,

PR: https://github.com/announcekitapp/announcekit-react/pull/37.

We'll be released the fix soon. Until then you can use v2.1.8.

2.1.8 sample: https://codesandbox.io/s/announcekit-react-2-0-demo-forked-kpqcj5?file=/src/index.tsx
