### ISSUE TITLE
React widgetOpen props not working

### ISSUE THREAD

**Issue by taltultc** [announcekitapp/announcekit-react#4]
Hi,

i'm trying to get the event widgetOpen like this:
 <AnnounceKit **widgetOpen={()=>console.log('open')}** catchClick=".click-trigger" widget="https://announcekit.app/widget/eL8Lm" />

this is not working, am i missing something?

**Comment by taltultc** [comment]
Solved. it's **onWidgetOpen** and not widgetOpen
You should fix your documentation

**Comment by namirali** [comment]
Fixed. Sorry about that :( Thank you for reporting @taltultc
