### ISSUE TITLE
Adding Youtube video throw error

### ISSUE THREAD

**Issue by taltultc** [announcekitapp/announcekit-react#5]
Hi,

If we add youtube video to Announcekit post we get this error on the client console:

**Uncaught DOMException: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.**

please add this flag: 'allow-presentation' to the youtube iframe

**Comment by namirali** [comment]
Changed our embed generation code to external API, I think that will solve this issue.
