### ISSUE TITLE
Listening for events is broken when dome changes

### ISSUE THREAD

**Issue by suchy** [announcekitapp/announcekit-react#7]
Hi,

I've got to issue where I can open announcekit just once. Looks like https://github.com/announcekitapp/announcekit-react/blob/master/src/index.tsx#L114 is broken when DOM changes (i.e using frontend router).

Maybe using refs will solve that issue?

**Comment by namirali** [comment]
Hi @suchy 

It makes sense. Also using `querySelector` in React is not something desired 🙈

I've added support for `ref` in **2.1.0**. You can find an example in readme.

Thanks.

**Comment by suchy** [comment]
Thanks for help ;-)
